### ISSUE TITLE
Assigning Roles - Courtney

### ISSUE THREAD

**Issue by ikaikastine** [ikaikastine/capstone-group-62#5]
Please add any/all of the areas you would like to contribute to:

**Comment by courtbonn** [comment]
- ~~General iOS UI Design~~
- ~~General Android UI Design~~
- ~~Integration of existing announcements~~ 
- ~~Integration of e-bulletins and handling the possible archive~~

**Comment by courtbonn** [comment]
- [x] Platform for iOS App 
- [x] Integration of e-bulletin/announcements
- [x] Organization of an iOS app
